[package]
name = "vrchatapi"
version = "1.17.5"
authors = ["vrchatapi.lpv0t@aries.fyi"]
description = "VRChat API Client for Rust"
license = "MIT"
edition = "2018"

[dependencies]
serde = {version = "^1.0", features = ["rc"]}
serde_derive = "^1.0"
serde_with = "^2.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }
[dependencies.reqwest]
version = "^0.11"
features = ["json", "cookies", "multipart"]

[dev-dependencies]
tokio = { version = '1', features = ['macros', 'rt-multi-thread'] }
[dependencies.log]
version = "0.4"
