/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDeletionLog {
    /// Typically \"Deletion requested\" or \"Deletion canceled\". Other messages like \"Deletion completed\" may exist, but are these are not possible to see as a regular user.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<std::sync::Arc<str>>,
    /// When the deletion is scheduled to happen, standard is 14 days after the request.
    #[serde(rename = "deletionScheduled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deletion_scheduled: Option<Option<std::sync::Arc<str>>>,
    /// Date and time of the deletion request.
    #[serde(rename = "dateTime", skip_serializing_if = "Option::is_none")]
    pub date_time: Option<std::sync::Arc<str>>,
}

impl AccountDeletionLog {
    pub fn new() -> AccountDeletionLog {
        AccountDeletionLog {
            message: None,
            deletion_scheduled: None,
            date_time: None,
        }
    }
}


