/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddGroupGalleryImageRequest {
    #[serde(rename = "fileId")]
    pub file_id: std::sync::Arc<str>,
}

impl AddGroupGalleryImageRequest {
    pub fn new(file_id: std::sync::Arc<str>) -> AddGroupGalleryImageRequest {
        AddGroupGalleryImageRequest {
            file_id,
        }
    }
}

