/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// ApiConfigAnnouncement : Public Announcement



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiConfigAnnouncement {
    /// Announcement name
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    /// Announcement text
    #[serde(rename = "text")]
    pub text: std::sync::Arc<str>,
}

impl ApiConfigAnnouncement {
    /// Public Announcement
    pub fn new(name: std::sync::Arc<str>, text: std::sync::Arc<str>) -> ApiConfigAnnouncement {
        ApiConfigAnnouncement {
            name,
            text,
        }
    }
}


