/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// Avatar : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Avatar {
    /// Not present from general serach `/avatars`, only on specific requests `/avatars/{avatarId}`.
    #[serde(rename = "assetUrl", skip_serializing_if = "Option::is_none")]
    pub asset_url: Option<std::sync::Arc<str>>,
    /// Not present from general serach `/avatars`, only on specific requests `/avatars/{avatarId}`. **Deprecation:** `Object` has unknown usage/fields, and is always empty. Use normal `Url` field instead.
    #[serde(rename = "assetUrlObject", skip_serializing_if = "Option::is_none")]
    pub asset_url_object: Option<serde_json::Value>,
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "authorId")]
    pub author_id: std::sync::Arc<str>,
    #[serde(rename = "authorName")]
    pub author_name: std::sync::Arc<str>,
    #[serde(rename = "created_at")]
    pub created_at: std::sync::Arc<str>,
    #[serde(rename = "description")]
    pub description: std::sync::Arc<str>,
    #[serde(rename = "featured")]
    pub featured: bool,
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "imageUrl")]
    pub image_url: std::sync::Arc<str>,
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    #[serde(rename = "releaseStatus")]
    pub release_status: crate::models::ReleaseStatus,
    ///  
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::tags::Tags>,
    #[serde(rename = "thumbnailImageUrl")]
    pub thumbnail_image_url: std::sync::Arc<str>,
    #[serde(rename = "unityPackageUrl")]
    pub unity_package_url: std::sync::Arc<str>,
    #[serde(rename = "unityPackageUrlObject")]
    pub unity_package_url_object: Box<crate::models::AvatarUnityPackageUrlObject>,
    #[serde(rename = "unityPackages")]
    pub unity_packages: Vec<crate::models::UnityPackage>,
    #[serde(rename = "updated_at")]
    pub updated_at: std::sync::Arc<str>,
    #[serde(rename = "version")]
    pub version: i32,
}

impl Avatar {
    /// 
    pub fn new(author_id: std::sync::Arc<str>, author_name: std::sync::Arc<str>, created_at: std::sync::Arc<str>, description: std::sync::Arc<str>, featured: bool, id: std::sync::Arc<str>, image_url: std::sync::Arc<str>, name: std::sync::Arc<str>, release_status: crate::models::ReleaseStatus, tags: Vec<crate::models::tags::Tags>, thumbnail_image_url: std::sync::Arc<str>, unity_package_url: std::sync::Arc<str>, unity_package_url_object: crate::models::AvatarUnityPackageUrlObject, unity_packages: Vec<crate::models::UnityPackage>, updated_at: std::sync::Arc<str>, version: i32) -> Avatar {
        Avatar {
            asset_url: None,
            asset_url_object: None,
            author_id,
            author_name,
            created_at,
            description,
            featured,
            id,
            image_url,
            name,
            release_status,
            tags,
            thumbnail_image_url,
            unity_package_url,
            unity_package_url_object: Box::new(unity_package_url_object),
            unity_packages,
            updated_at,
            version,
        }
    }
}


