/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupRoleRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<std::sync::Arc<str>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<std::sync::Arc<str>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<std::sync::Arc<str>>,
    #[serde(rename = "isSelfAssignable", skip_serializing_if = "Option::is_none")]
    pub is_self_assignable: Option<bool>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<std::sync::Arc<str>>>,
}

impl CreateGroupRoleRequest {
    pub fn new() -> CreateGroupRoleRequest {
        CreateGroupRoleRequest {
            id: None,
            name: None,
            description: None,
            is_self_assignable: None,
            permissions: None,
        }
    }
}


