/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFileRequest {
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    #[serde(rename = "mimeType")]
    pub mime_type: models::MimeType,
    #[serde(rename = "extension")]
    pub extension: std::sync::Arc<str>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<std::sync::Arc<str>>>,
}

impl CreateFileRequest {
    pub fn new(name: std::sync::Arc<str>, mime_type: models::MimeType, extension: std::sync::Arc<str>) -> CreateFileRequest {
        CreateFileRequest {
            name,
            mime_type,
            extension,
            tags: None,
        }
    }
}

