/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupAnnouncementRequest {
    /// Announcement title
    #[serde(rename = "title")]
    pub title: std::sync::Arc<str>,
    /// Announcement text
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<std::sync::Arc<str>>,
    #[serde(rename = "imageId", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<std::sync::Arc<str>>,
    /// Send notification to group members.
    #[serde(rename = "sendNotification", skip_serializing_if = "Option::is_none")]
    pub send_notification: Option<bool>,
}

impl CreateGroupAnnouncementRequest {
    pub fn new(title: std::sync::Arc<str>) -> CreateGroupAnnouncementRequest {
        CreateGroupAnnouncementRequest {
            title,
            text: None,
            image_id: None,
            send_notification: None,
        }
    }
}


