/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// File : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    #[serde(rename = "extension")]
    pub extension: std::sync::Arc<str>,
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "mimeType")]
    pub mime_type: crate::models::MimeType,
    /// 
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "ownerId")]
    pub owner_id: std::sync::Arc<str>,
    ///  
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::tags::Tags>,
    ///  
    #[serde(rename = "versions")]
    pub versions: Vec<crate::models::FileVersion>,
}

impl File {
    /// 
    pub fn new(extension: std::sync::Arc<str>, id: std::sync::Arc<str>, mime_type: crate::models::MimeType, name: std::sync::Arc<str>, owner_id: std::sync::Arc<str>, tags: Vec<crate::models::tags::Tags>, versions: Vec<crate::models::FileVersion>) -> File {
        File {
            extension,
            id,
            mime_type,
            name,
            owner_id,
            tags,
            versions,
        }
    }
}


