/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// FileUploadUrl : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUploadUrl {
    /// 
    #[serde(rename = "url")]
    pub url: std::sync::Arc<str>,
}

impl FileUploadUrl {
    /// 
    pub fn new(url: std::sync::Arc<str>) -> FileUploadUrl {
        FileUploadUrl {
            url,
        }
    }
}


