/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupGallery {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<std::sync::Arc<str>>,
    /// Name of the gallery.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<std::sync::Arc<str>>,
    /// Description of the gallery.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<std::sync::Arc<str>>,
    /// Whether the gallery is members only.
    #[serde(rename = "membersOnly", skip_serializing_if = "Option::is_none")]
    pub members_only: Option<bool>,
    ///  
    #[serde(rename = "roleIdsToView", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_ids_to_view: Option<Option<Vec<std::sync::Arc<str>>>>,
    ///  
    #[serde(rename = "roleIdsToSubmit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_ids_to_submit: Option<Option<Vec<std::sync::Arc<str>>>>,
    ///  
    #[serde(rename = "roleIdsToAutoApprove", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_ids_to_auto_approve: Option<Option<Vec<std::sync::Arc<str>>>>,
    ///  
    #[serde(rename = "roleIdsToManage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_ids_to_manage: Option<Option<Vec<std::sync::Arc<str>>>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<std::sync::Arc<str>>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<std::sync::Arc<str>>,
}

impl GroupGallery {
    pub fn new() -> GroupGallery {
        GroupGallery {
            id: None,
            name: None,
            description: None,
            members_only: None,
            role_ids_to_view: None,
            role_ids_to_submit: None,
            role_ids_to_auto_approve: None,
            role_ids_to_manage: None,
            created_at: None,
            updated_at: None,
        }
    }
}


