/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// InfoPush : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoPush {
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "isEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "releaseStatus")]
    pub release_status: crate::models::ReleaseStatus,
    #[serde(rename = "priority")]
    pub priority: i32,
    ///  
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::tags::Tags>,
    #[serde(rename = "data")]
    pub data: Box<crate::models::InfoPushData>,
    /// Unknown usage, MD5
    #[serde(rename = "hash")]
    pub hash: std::sync::Arc<str>,
    #[serde(rename = "createdAt")]
    pub created_at: std::sync::Arc<str>,
    #[serde(rename = "updatedAt")]
    pub updated_at: std::sync::Arc<str>,
    /// 
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<std::sync::Arc<str>>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<std::sync::Arc<str>>,
}

impl InfoPush {
    /// 
    pub fn new(id: std::sync::Arc<str>, is_enabled: bool, release_status: crate::models::ReleaseStatus, priority: i32, tags: Vec<crate::models::tags::Tags>, data: crate::models::InfoPushData, hash: std::sync::Arc<str>, created_at: std::sync::Arc<str>, updated_at: std::sync::Arc<str>) -> InfoPush {
        InfoPush {
            id,
            is_enabled,
            release_status,
            priority,
            tags,
            data: Box::new(data),
            hash,
            created_at,
            updated_at,
            start_date: None,
            end_date: None,
        }
    }
}


