/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceShortNameResponse {
    #[serde(rename = "secureName")]
    pub secure_name: std::sync::Arc<str>,
    #[serde(rename = "shortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<std::sync::Arc<str>>,
}

impl InstanceShortNameResponse {
    pub fn new(secure_name: std::sync::Arc<str>) -> InstanceShortNameResponse {
        InstanceShortNameResponse {
            secure_name,
            short_name: None,
        }
    }
}


