/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    /// Either a AvatarID, LicenseGroupID, PermissionID or ProductID. This depends on the `forType` field.
    #[serde(rename = "forId")]
    pub for_id: std::sync::Arc<str>,
    #[serde(rename = "forType")]
    pub for_type: crate::models::LicenseType,
    #[serde(rename = "forName")]
    pub for_name: std::sync::Arc<str>,
    #[serde(rename = "forAction")]
    pub for_action: crate::models::LicenseAction,
}

impl License {
    pub fn new(for_id: std::sync::Arc<str>, for_type: crate::models::LicenseType, for_name: std::sync::Arc<str>, for_action: crate::models::LicenseAction) -> License {
        License {
            for_id,
            for_type,
            for_name,
            for_action,
        }
    }
}


