/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// LicenseGroup : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseGroup {
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    #[serde(rename = "description")]
    pub description: std::sync::Arc<str>,
    #[serde(rename = "licenses")]
    pub licenses: Vec<crate::models::License>,
}

impl LicenseGroup {
    /// 
    pub fn new(id: std::sync::Arc<str>, name: std::sync::Arc<str>, description: std::sync::Arc<str>, licenses: Vec<crate::models::License>) -> LicenseGroup {
        LicenseGroup {
            id,
            name,
            description,
            licenses,
        }
    }
}


