/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// LimitedWorld : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitedWorld {
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "authorId")]
    pub author_id: std::sync::Arc<str>,
    #[serde(rename = "authorName")]
    pub author_name: std::sync::Arc<str>,
    #[serde(rename = "capacity")]
    pub capacity: i32,
    #[serde(rename = "recommendedCapacity", skip_serializing_if = "Option::is_none")]
    pub recommended_capacity: Option<i32>,
    #[serde(rename = "created_at")]
    pub created_at: std::sync::Arc<str>,
    #[serde(rename = "favorites")]
    pub favorites: i32,
    #[serde(rename = "visits", skip_serializing_if = "Option::is_none")]
    pub visits: Option<i32>,
    #[serde(rename = "heat")]
    pub heat: i32,
    /// WorldID be \"offline\" on User profiles if you are not friends with that user.
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "imageUrl")]
    pub image_url: std::sync::Arc<str>,
    #[serde(rename = "labsPublicationDate")]
    pub labs_publication_date: std::sync::Arc<str>,
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    #[serde(rename = "occupants")]
    pub occupants: i32,
    #[serde(rename = "organization")]
    pub organization: std::sync::Arc<str>,
    #[serde(rename = "popularity")]
    pub popularity: i32,
    #[serde(rename = "previewYoutubeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preview_youtube_id: Option<Option<std::sync::Arc<str>>>,
    #[serde(rename = "publicationDate")]
    pub publication_date: std::sync::Arc<str>,
    #[serde(rename = "releaseStatus")]
    pub release_status: crate::models::ReleaseStatus,
    ///  
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::tags::Tags>,
    #[serde(rename = "thumbnailImageUrl")]
    pub thumbnail_image_url: std::sync::Arc<str>,
    ///  
    #[serde(rename = "unityPackages")]
    pub unity_packages: Vec<crate::models::LimitedUnityPackage>,
    #[serde(rename = "updated_at")]
    pub updated_at: std::sync::Arc<str>,
    #[serde(rename = "udonProducts", skip_serializing_if = "Option::is_none")]
    pub udon_products: Option<Vec<std::sync::Arc<str>>>,
}

impl LimitedWorld {
    /// 
    pub fn new(author_id: std::sync::Arc<str>, author_name: std::sync::Arc<str>, capacity: i32, created_at: std::sync::Arc<str>, favorites: i32, heat: i32, id: std::sync::Arc<str>, image_url: std::sync::Arc<str>, labs_publication_date: std::sync::Arc<str>, name: std::sync::Arc<str>, occupants: i32, organization: std::sync::Arc<str>, popularity: i32, publication_date: std::sync::Arc<str>, release_status: crate::models::ReleaseStatus, tags: Vec<crate::models::tags::Tags>, thumbnail_image_url: std::sync::Arc<str>, unity_packages: Vec<crate::models::LimitedUnityPackage>, updated_at: std::sync::Arc<str>) -> LimitedWorld {
        LimitedWorld {
            author_id,
            author_name,
            capacity,
            recommended_capacity: None,
            created_at,
            favorites,
            visits: None,
            heat,
            id,
            image_url,
            labs_publication_date,
            name,
            occupants,
            organization,
            popularity,
            preview_youtube_id: None,
            publication_date,
            release_status,
            tags,
            thumbnail_image_url,
            unity_packages,
            updated_at,
            udon_products: None,
        }
    }
}


