/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationDetailRequestInviteResponse {
    #[serde(rename = "inResponseTo")]
    pub in_response_to: std::sync::Arc<str>,
    /// Used when using InviteMessage Slot.
    #[serde(rename = "requestMessage", skip_serializing_if = "Option::is_none")]
    pub request_message: Option<std::sync::Arc<str>>,
}

impl NotificationDetailRequestInviteResponse {
    pub fn new(in_response_to: std::sync::Arc<str>) -> NotificationDetailRequestInviteResponse {
        NotificationDetailRequestInviteResponse {
            in_response_to,
            request_message: None,
        }
    }
}


