/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationDetailInviteResponse {
    #[serde(rename = "inResponseTo")]
    pub in_response_to: std::sync::Arc<str>,
    #[serde(rename = "responseMessage")]
    pub response_message: std::sync::Arc<str>,
}

impl NotificationDetailInviteResponse {
    pub fn new(in_response_to: std::sync::Arc<str>, response_message: std::sync::Arc<str>) -> NotificationDetailInviteResponse {
        NotificationDetailInviteResponse {
            in_response_to,
            response_message,
        }
    }
}


