/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PastDisplayName {
    #[serde(rename = "displayName")]
    pub display_name: std::sync::Arc<str>,
    #[serde(rename = "updated_at")]
    pub updated_at: std::sync::Arc<str>,
}

impl PastDisplayName {
    pub fn new(display_name: std::sync::Arc<str>, updated_at: std::sync::Arc<str>) -> PastDisplayName {
        PastDisplayName {
            display_name,
            updated_at,
        }
    }
}


