/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// Permission : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "name")]
    pub name: std::sync::Arc<str>,
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "ownerId")]
    pub owner_id: std::sync::Arc<str>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl Permission {
    /// 
    pub fn new(id: std::sync::Arc<str>, name: std::sync::Arc<str>, owner_id: std::sync::Arc<str>) -> Permission {
        Permission {
            id,
            name,
            owner_id,
            data: None,
        }
    }
}


