/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<std::sync::Arc<str>>,
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl Response {
    pub fn new(status_code: i32) -> Response {
        Response {
            message: None,
            status_code,
        }
    }
}


