/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// TransactionSteamWalletInfo : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSteamWalletInfo {
    #[serde(rename = "state")]
    pub state: std::sync::Arc<str>,
    #[serde(rename = "country")]
    pub country: std::sync::Arc<str>,
    #[serde(rename = "currency")]
    pub currency: std::sync::Arc<str>,
    #[serde(rename = "status")]
    pub status: std::sync::Arc<str>,
}

impl TransactionSteamWalletInfo {
    /// 
    pub fn new(state: std::sync::Arc<str>, country: std::sync::Arc<str>, currency: std::sync::Arc<str>, status: std::sync::Arc<str>) -> TransactionSteamWalletInfo {
        TransactionSteamWalletInfo {
            state,
            country,
            currency,
            status,
        }
    }
}


