/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

/// TransactionAgreement : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionAgreement {
    #[serde(rename = "agreementId")]
    pub agreement_id: std::sync::Arc<str>,
    #[serde(rename = "itemId")]
    pub item_id: f32,
    /// This is NOT TransactionStatus, but whatever Steam return.
    #[serde(rename = "status")]
    pub status: std::sync::Arc<str>,
    #[serde(rename = "period")]
    pub period: std::sync::Arc<str>,
    #[serde(rename = "frequency")]
    pub frequency: f32,
    #[serde(rename = "billingType")]
    pub billing_type: std::sync::Arc<str>,
    #[serde(rename = "startDate")]
    pub start_date: std::sync::Arc<str>,
    #[serde(rename = "endDate")]
    pub end_date: std::sync::Arc<str>,
    #[serde(rename = "recurringAmt")]
    pub recurring_amt: f32,
    #[serde(rename = "currency")]
    pub currency: std::sync::Arc<str>,
    #[serde(rename = "timeCreated")]
    pub time_created: std::sync::Arc<str>,
    #[serde(rename = "nextPayment")]
    pub next_payment: std::sync::Arc<str>,
    #[serde(rename = "lastPayment")]
    pub last_payment: std::sync::Arc<str>,
    #[serde(rename = "lastAmount")]
    pub last_amount: f32,
    #[serde(rename = "lastAmountVat")]
    pub last_amount_vat: f32,
    #[serde(rename = "outstanding")]
    pub outstanding: f32,
    #[serde(rename = "failedAttempts")]
    pub failed_attempts: f32,
}

impl TransactionAgreement {
    /// 
    pub fn new(agreement_id: std::sync::Arc<str>, item_id: f32, status: std::sync::Arc<str>, period: std::sync::Arc<str>, frequency: f32, billing_type: std::sync::Arc<str>, start_date: std::sync::Arc<str>, end_date: std::sync::Arc<str>, recurring_amt: f32, currency: std::sync::Arc<str>, time_created: std::sync::Arc<str>, next_payment: std::sync::Arc<str>, last_payment: std::sync::Arc<str>, last_amount: f32, last_amount_vat: f32, outstanding: f32, failed_attempts: f32) -> TransactionAgreement {
        TransactionAgreement {
            agreement_id,
            item_id,
            status,
            period,
            frequency,
            billing_type,
            start_date,
            end_date,
            recurring_amt,
            currency,
            time_created,
            next_payment,
            last_payment,
            last_amount,
            last_amount_vat,
            outstanding,
            failed_attempts,
        }
    }
}


