/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorEmailCode {
    #[serde(rename = "code")]
    pub code: std::sync::Arc<str>,
}

impl TwoFactorEmailCode {
    pub fn new(code: std::sync::Arc<str>) -> TwoFactorEmailCode {
        TwoFactorEmailCode {
            code,
        }
    }
}


