/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateInviteMessageRequest {
    #[serde(rename = "message")]
    pub message: std::sync::Arc<str>,
}

impl UpdateInviteMessageRequest {
    pub fn new(message: std::sync::Arc<str>) -> UpdateInviteMessageRequest {
        UpdateInviteMessageRequest {
            message,
        }
    }
}

