/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSubscription : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSubscription {
    #[serde(rename = "id")]
    pub id: std::sync::Arc<str>,
    #[serde(rename = "transactionId")]
    pub transaction_id: std::sync::Arc<str>,
    /// Which \"Store\" it came from. Right now only Stores are \"Steam\" and \"Admin\".
    #[serde(rename = "store")]
    pub store: std::sync::Arc<str>,
    #[serde(rename = "steamItemId", skip_serializing_if = "Option::is_none")]
    pub steam_item_id: Option<std::sync::Arc<str>>,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "description")]
    pub description: std::sync::Arc<str>,
    #[serde(rename = "period")]
    pub period: models::SubscriptionPeriod,
    #[serde(rename = "tier")]
    pub tier: f64,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "status")]
    pub status: models::TransactionStatus,
    #[serde(rename = "starts", skip_serializing_if = "Option::is_none")]
    pub starts: Option<std::sync::Arc<str>>,
    #[serde(rename = "expires")]
    pub expires: std::sync::Arc<str>,
    #[serde(rename = "created_at")]
    pub created_at: std::sync::Arc<str>,
    #[serde(rename = "updated_at")]
    pub updated_at: std::sync::Arc<str>,
    #[serde(rename = "licenseGroups")]
    pub license_groups: Vec<std::sync::Arc<str>>,
    #[serde(rename = "isGift")]
    pub is_gift: bool,
}

impl UserSubscription {
    pub fn new(id: std::sync::Arc<str>, transaction_id: std::sync::Arc<str>, store: std::sync::Arc<str>, amount: f64, description: std::sync::Arc<str>, period: models::SubscriptionPeriod, tier: f64, active: bool, status: models::TransactionStatus, expires: std::sync::Arc<str>, created_at: std::sync::Arc<str>, updated_at: std::sync::Arc<str>, license_groups: Vec<std::sync::Arc<str>>, is_gift: bool) -> UserSubscription {
        UserSubscription {
            id,
            transaction_id,
            store,
            steam_item_id: None,
            amount,
            description,
            period,
            tier,
            active,
            status,
            starts: None,
            expires,
            created_at,
            updated_at,
            license_groups,
            is_gift,
        }
    }
}

